# Generated by Django 5.2.4 on 2025-07-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelspecification',
            name='status',
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='inspectionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='formNumber',
            field=models.CharField(max_length=50),
        ),
    ]
